name = "my-mail"
main = "src/index.js"
compatibility_date = "2025-06-01"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "my-mail-db"
database_id = "522625c4-f100-44df-92f3-412e62f0b675"

[[kv_namespaces]]
binding = "kv"
id = "9f9bf9ad53244481a77f9dbb095b192e"

[[r2_buckets]]
binding = "r2"
bucket_name = "my-mail-attachments"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[vars]
# Domain email Anda (opsional, bisa diisi nanti)
# domain = ["example.com"]
# Email admin
# admin = "admin@example.com"
jwt_secret = "CHANGE_THIS_TO_RANDOM_STRING"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"